### PR TITLE
Add classic description

### PR DESCRIPTION
**Pull request by agix**
PR done on elastalert (https://github.com/Yelp/elastalert/pull/2263) but maybe it should be done here before.

Handle matches merge in one alert with combined artifacts when aggregation is set. (see elastalert PR for more details)

### CODE REVIEW

**Comment by agix** [comment]
Hi,

thx for your review.

I was wondering if the regex match every potential of fields used by python
format. like nested nested fields in nested array etc...

If the issue was just not to crash the whole alert when observable match
key doesn't exist. Passing on the exception should do the tricks.

Maybe I should replace the print by a proper logging call.

what do you think.


Le dim. 2 juin 2019 à 12:41, Daniel Browne <notifications@github.com> a
écrit :

**Comment by agix** [comment]
Just realized I pasted the wrong link to the pr on elastalert. https://github.com/Yelp/elastalert/pull/2263

You should find more explanation here.

**Comment by danielbrowne** [comment]
Thanks for the link to the PR.
I missed that the exception raise was changed to a print, that should have the same effect and I am OK with that. You can change it to logging if you want to, but I think it is fine as is.

**Comment by agix** [comment]
Ok perfect, I prefer to let the print then.

What's the next step ? Should I close my PR on elastalert and let you push back this alerter into elastalert by yourselves ?

**Comment by danielbrowne** [comment]
If you have already made a PR on Elastalert then I see no reason to not to leave that one open. 
Thank you for the improvements.

**Pull request merged**
